name: python-app-3-cicd

on:
  push:
    paths:
      - 'src/**'
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Shorten Commit ID
        shell: bash
        run: |
          set -euo pipefail
          # 7 karakterlik kısa SHA üret
          SHORT_SHA="$(echo "${GITHUB_SHA}" | cut -c1-7)"
          # Boşsa hata ver (tag boş kalmasın)
          if [ -z "$SHORT_SHA" ]; then
            echo "SHORT_SHA boş! GITHUB_SHA: ${GITHUB_SHA}"
            exit 1
          fi
          echo "COMMIT_ID=$SHORT_SHA" >> "$GITHUB_ENV"
          echo "Kullanılacak tag: $SHORT_SHA"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: gokhangurbuz/python-app-3:${{ env.COMMIT_ID }}
    outputs:
      commit_id: ${{ env.COMMIT_ID }}
  
  cd:
    needs: ci
    runs-on: self-hosted
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Modify values file
        shell: bash
        run: |
          echo ${{ needs.ci.outputs.commit_id }}
          pip install yq
          yq -Yi '.image.tag = "${{ needs.ci.outputs.commit_id }}"' charts/python-app-3/values-dev.yaml

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update image tag to ${{ needs.ci.outputs.commit_id }}"

      - name: Install argocd
        shell: bash
        run: |
          curl -ksSL -o argocd https://argocd-server.argocd.svc.cluster.local/download/argocd-linux-arm64
          chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd

      - name: argocd login
        shell: bash
        run: |
          argocd login argocd-server.argocd \
            --insecure  \
            --grpc-web \
            --username admin \
            --password  ${{ secrets.ARGOCD_PASSWORD }}

      - name: Ensure argocd repo and app
        shell: bash
        run: |

          # Connects the argocd repo
          repo="https://github.com/gokhan-gurbuz/python-app-3.git"
          argocd repo list | grep -q $repo || argocd repo add $repo

          # Creates the argocd app
          argocd app get python-app-3 || argocd app create python-app-3 \
            --repo $repo \
            --path charts/python-app-3 \
            --dest-namespace dev \
            --dest-server https://kubernetes.default.svc \
            --values values-dev.yaml \
            --revision main \
            --sync-policy manual \
            --sync-option CreateNamespace=true

      - name: Argocd app sync
        shell: bash
        run: |
          argocd app sync python-app-3
          argocd app wait python-app-3 --timeout 180
